# copyright: 2024 European Union
# license: LICENSE.txt
name: cmts_sst_applications
channels:
  - conda-forge
  - cmts
  - eumetsat
  - coecms
dependencies:
  # Core
#  - conda-forge::bokeh=3.2.1
  - conda-forge::cartopy
#  - conda-forge::cmocean
#  - conda-forge::dask
#  - conda-forge::distributed
#  - conda-forge::hda
#  - conda-forge::ipywidgets
#  - conda-forge::jupyterlab
  - conda-forge::matplotlib
  - conda-forge::netcdf4
#  - conda-forge::python=3.10
  - conda-forge::scipy
  - conda-forge::xarray
  # External
  - cmts::eumartools
  - eumetsat::eumdac
#  - coecms::xmhw
  # Extension
  - conda-forge::copernicusmarine
  - conda-forge::pandas
  - conda-forge::xcube